### ISSUE TITLE
Render many containers in a better way. 

### ISSUE THREAD

**Issue by megastef** [ManoMarks/docker-swarm-visualizer#20]
Running 100 containers on 4 nodes: 

![bildschirmfoto 2016-08-30 um 15 59 19](https://cloud.githubusercontent.com/assets/7289505/18092082/34905514-6ecb-11e6-8f34-5244a45cdd93.png)

**Comment by ManoMarks** [comment]
Feel free to submit a pull request

**Comment by ManoMarks** [comment]
#37

**Comment by ManoMarks** [comment]
Since I closed the PR for lack of action, I'm closing this issue too. Feel free to submit another PR along the lines of what I suggested in #37
