### ISSUE TITLE
Starts, but nothing displayed

### ISSUE THREAD

**Issue by kylegordon** [ManoMarks/docker-swarm-visualizer#21]
Hi,

I have started visualizer with this...

`docker run --name=visualizer -it -d -p 9000:9000 -e HOST=10.2.10.34 -e PORT=9000 -v /var/run/docker.sock:/var/run/docker.sock manomarks/visualizer`

and it shows up correctly as running, but has an undefined error (investigations show this is due to process.env.DOCKER_HOST being empty)

10.2.10.34 is the IP of our swarm master, although as below the master runs visualizer on swarm-node-02 at 10.2.10.44

```
90aa79e4b705        manomarks/visualizer           "npm start"              3 minutes ago       Up 3 minutes        8080/tcp, 10.2.10.44:9000->9000/tcp   swarm-node-02/visualizer

npm info it worked if it ends with ok
npm info using npm@2.14.4
npm info using node@v4.1.2
npm info prestart swarmVisualizer@0.0.1
npm info start swarmVisualizer@0.0.1

> swarmVisualizer@0.0.1 start /app
> node server.js

undefined
```

This is on Docker 1.12, Swarm 1.2.5, deployed via boot2docker 1.12.0. 

The end result is a screen identical to that in #19

**Comment by raykrueger** [comment]
I think you need to deploy this on a master node, with the master node IP in the url.

**Comment by tibmeister** [comment]
I'm going to echo raykruger's comments.  I have the identical screen that he has from issue #19.  I am using the IP address of the host's eth0 as the HOST variable.  I am using Docker 1.12.1 and have an active swarm.  All this is running on CentOS7.  This whole "undefined" is kinda disturbing...

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Comment by ManoMarks** [comment]
@tibmeister are you running on a master node?

**Comment by tibmeister** [comment]
Yep, and just found out what is going on, the HOST variable must match what is being used in the browser.  I was using HOST=IP and using FQDN in the browser URL.  Once I switched the HOST variable using FQDN it's working.  So, that's an interesting thing...

**Comment by kylegordon** [comment]
Mornings,

So part of my problem was that I was running swarm master and agents upgraded from 0.11 to 0.12, and not using the built in Docker Engine swarm mode. I've since destroyed the cluster, and rebuilt using built in Swarm, and it works.

I can confirm what @tibmeister says though, you have to match $HOST in the browser url in order to obtain any output from it.

My issue is closed, but whether this is another one... I'll leave that to @ManoMarks :-)

**Comment by Laxman-SM** [comment]
+1 @tibmeister

**Comment by johnharris85** [comment]
`undefined` is crappy coding on my part. I just print the contents of the `DOCKER_HOST` environment variable as my of a PR a while ago and forgot to remove the line. It doesn't need to be set so the `undefined` you guys are seeing here is irrelevant / red herring.
