### ISSUE TITLE
node hostname not scaleable

### ISSUE THREAD

**Issue by michaelwilde** [ManoMarks/docker-swarm-visualizer#24]
Hey Mano... love the new improvements.   I have some long hostnames like es.demo.splunkninja.com.  on four nodes, they tend to clog each other up.   cmd +- doesn't have an effect.
![screenshot 2016-09-07 11 09 45](https://cloud.githubusercontent.com/assets/213230/18319527/b856c664-74eb-11e6-8738-1872d58c14ae.png)

**Comment by Josh-West-Bose** [comment]
+1

**Comment by rogerwelin** [comment]
+1

**Comment by ManoMarks** [comment]
Ah good issue. What's the expected behavior?

**Comment by michaelwilde** [comment]
scale it down.  I know wrapping would be hard unless you to wrap on a "."
Or heck you might just be able to hack a "scale font" button on there where people could just click to make it smaller and you just scale the CSS font size value.     Great app tho.

**Comment by ManoMarks** [comment]
OK, thanks I'll take a look at it.

**Comment by ManoMarks** [comment]
I added a `text-overflow` on `.node-meta` to put an ellipsis at end of long names. I'd welcome a PR that allowed for flexible font sizes.
