### ISSUE TITLE
Can we display container name rather than image name in the visualizer?

### ISSUE THREAD

**Issue by deanmax** [ManoMarks/docker-swarm-visualizer#29]

**Comment by ManoMarks** [comment]
@deanmax   Container names in Swarm Mode are not that interesting. However, service name might be more interesting. Is that what you're going for?

**Comment by deanmax** [comment]
@ManoMarks, what I want to see in the visualizer is the service name that I manually specified when creating the service. For now only image name of the service is displayed on the visualizer dashboard.

**Comment by ManoMarks** [comment]
SGTM

**Comment by pmcnett** [comment]
+1 service name. I have multiple services all using the same container and container tag.

**Comment by beenanner** [comment]
Running `docker service create --name my-test-service memcached` will produce the following:

![service-name](https://cloud.githubusercontent.com/assets/723985/19953823/cfd79dde-a148-11e6-842f-e8165f9a3781.jpg)

**Comment by ManoMarks** [comment]
#38
