### ISSUE TITLE
Visualizer doesn't reflect when a node has been promoted

### ISSUE THREAD

**Issue by programmerq** [ManoMarks/docker-swarm-visualizer#30]
After promoting a node

    docker@node1:~$ docker node promote node2
    Node node2 promoted to a manager in the swarm.

The visualizer still shows it is a worker:

![image](https://cloud.githubusercontent.com/assets/37278/18975044/8e6e3fc8-8664-11e6-87ef-26dae6054afa.png)

After refreshing the visualizer, it shows the correct role:

![image](https://cloud.githubusercontent.com/assets/37278/18975066/b4cddf16-8664-11e6-92de-21b22cf72593.png)

**Comment by ManoMarks** [comment]
Fixed
