### ISSUE TITLE
memory display less than 1GB (for Pi clusters etc)

### ISSUE THREAD

**Issue by doughadfield** [ManoMarks/docker-swarm-visualizer#49]
![viz](https://cloud.githubusercontent.com/assets/6051108/21882731/c3405696-d8a3-11e6-9d5b-13995a78ee49.jpg)
Hi, this is an excellent app for simply illustrating docker clusters in a "lab" environment. In these environments Raspberry Pi clusters are common. However most Pis (Zeros) have less than 1GB memory, but the recent mod to display memory in GB displays "0" for memory sizes less than 1GB. Please can the memory display line be tweaked slightly to show fractions of GB (0.5GB) for 512MB nodes?

thanks again for an excellent tool

Doug

**Comment by getvivekv** [comment]
+ 1. Same here.

**Comment by ManoMarks** [comment]
Fixed, currently building. Will show 3 decimal places
