### ISSUE TITLE
no such image : manomarks/visu… on 1.13 

### ISSUE THREAD

**Issue by wannaknowmo** [ManoMarks/docker-swarm-visualizer#50]
hi,

i upgraded my docker swarm engine to 1.13.0 yesterday and the visualizer is no longer working for me.
if i rollback to  1.12.6 with the same viz service create cmd &  it works.

docker service create  --name=viz   --publish=5001:8080/tcp   --constraint=node.role==manager   --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock manomarks/visualizer
p2nphhjreujdw6nqk06xq50xq

j588605rxyfk  viz.1      manomarks/visualizer:latest  totod  Ready          Rejected 3 seconds ago   "No such image: manomarks/visu…"  
himt2p9lf4g6   \_ viz.1  manomarks/visualizer:latest  totod  Shutdown       Rejected 9 seconds ago   "No such image: manomarks/visu…"  
zdsybsaop9nr   \_ viz.1  manomarks/visualizer:latest  totod  Shutdown       Rejected 13 seconds ago  "No such image: manomarks/visu…"  
uxticfavukmo   \_ viz.1  manomarks/visualizer:latest  totod  Shutdown       Rejected 19 seconds ago  "No such image: manomarks/visu…"  
raqf1k63srq2   \_ viz.1  manomarks/visualizer:latest  totod  Shutdown       Rejected 24 seconds ago  "No such image: manomarks/visu…"  

 docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker service ls
ID            NAME     MODE        REPLICAS  IMAGE
8h38a7w1bqkw  ansible  replicated  13/13     ansible2.2
p2nphhjreujd  viz      replicated  0/1       manomarks/visualizer:latest

uname -r
3.10.0-514.2.2.el7.x86_64

-Alex

**Comment by ManoMarks** [comment]
@wannaknowmo I've updated the images, can you check now?

**Comment by wannaknowmo** [comment]
hi,

sorry same error.

Jan 24 20:11:17 totod dockerd: time="2017-01-24T20:11:17.653444322-06:00" level=error msg="fatal task error" error="No such image: manomarks/visualizer@sha256:65e2a72f454bcc19c4bd818fef4ae776d1f6bb3249eecf32947358d0d4983372" module="node/agent/taskmanager" task.id=jdq7up49h9vresjdc79hv9cnq

one thing to keep in mind i don't have access to github to do a pull from my docker host so i save your image in a tarball & load it manually(docker save/docker load).
when i do the same with 1.12.6 it works fine.
i also do a save/load with a jenkins image and it works fine with 1.13

thank you for taking a l00k

Alex

**Comment by ManoMarks** [comment]
Have you pulled the latest version of manomarks/visualizer?
```
docker pull manomarks/visualizer
```
And then save and load that one?

**Comment by wannaknowmo** [comment]
yes, i pulled it again with the same result.

i wipe out everything in /var/lib/docker across all the node in the docker swarm & it worked!!!.

thank you very much for your help

**Comment by ManoMarks** [comment]
Great!
