### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by boydj** [ManoMarks/docker-swarm-visualizer#8]
$ docker run -it -d -p 8080:8080 -e HOST=ucp-controller-540dd7c4.east1a.prod -e constraint:node==ucp-controller-540dd7c4.east1a.prod -v /var/run/docker.sock:/var/run/docker.sock manomarks/visualizer

10:50 $ docker logs -f 960f0ab11bd8
npm info it worked if it ends with ok
npm info using npm@2.14.4
npm info using node@v4.1.2
npm info prestart swarmVisualizer@0.0.1
npm info start swarmVisualizer@0.0.1

> swarmVisualizer@0.0.1 start /app
> node server.js

undefined:1
404 page not found
    ^

SyntaxError: Unexpected token p
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/app/server.js:49:36)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

npm info swarmVisualizer@0.0.1 Failed to exec start script
npm ERR! Linux 3.10.0-327.18.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! swarmVisualizer@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swarmVisualizer@0.0.1 start script 'node server.js'.
npm ERR! This is most likely a problem with the swarmVisualizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls swarmVisualizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by ManoMarks** [comment]
Sorry bug is really old, so I'm closing it. Please reopen if still an issue
